### PR TITLE
leveraging istanbul and coveralls.

### PR DESCRIPTION
**Pull request by jhowardjr**
Leveraging istanbul and coveralls to measure and maintain the testing coverage.

### CODE REVIEW

**Comment by jhowardjr** [comment]
You should continue to run ```npm test``` locally. Istanbul (nyc) is a tool for generating test coverage reports. Testing coverage is a measurement used to provide what percentage of the software has been exercised. 0% coverage would mean none of the code is tested and 100% coverage means all lines of code have been exercised. [Coveralls](https://github.com/marketplace/coveralls) for the purpose of this project is a just an integration tool that will provide us statistics related to our test coverage. You won't be able to use ```npm run coveralls``` locally without the repo_token. Generally, that value wouldn't be made public, but I can regenerate a new one after you test it on your system. Here's what you can do:

1) create a .coveralls.yml in the root
2) add the following in the file: ```repo_token: mCFTHwHVzFCm0nGJyKizwAZac2WOVmqad```
3) run ```npm run coveralls```
4) Go to https://coveralls.io/github/jhowardjr/variadic.js 

There you should notice the build number increasing everytime you run the coveralls script.

screen shot 2018-01-28 at 2 48 56 pm

Is ```npm test``` running ok on your windows system? You should see additional information after running that command.

screen shot 2018-01-28 at 2 52 40 pm

If you continue to have issues I'll download windows and take a look. Let me know if ```npm run coveralls``` works with the .coveralls.yml file, because I'll need to generate a new token.

**Comment by jmbothe** [comment]
Ahhhhhhh ok. So, it looks like i should have run `npm test` BEFORE trying '`npm run coveralls`. `npm test` created the `.nyc_output` folder, so now `npm run coveralls` is working fine on my machine. So as far as that is concerned, all is good. I'll review and approve this PR.

and you can go ahead and regenerate a new key. thanks so much for accomodating. it was cool to see how all that works.

On a related topic, I have a question: that screenshot above of the `npm test` output, is that recent? Cuz my output is showing much lower `% funcs` for several of the files (all of which I coded, of course. haha). Also I got a long list of errors before the coverage table printed. If the expected output is 100% for everything, let me know and I will dig deeper into what my issue might be.

Isn't it fun collaborating with a noob running a Windows dev environment? hahahahaha!

**Comment by jhowardjr** [comment]
Hmmm. The feature-coverage branch should be 100% across the board. I think I'll need to download windows to see if I get something different. What version of windows are you running?

**Comment by jhowardjr** [comment]
Also, it looks like you need to accept the invite here to gain write access to the repo. You should be able to do that here https://github.com/jhowardjr/variadic.js/invitations.

**Comment by jmbothe** [comment]
I'm running Windows 10, node v8.9.4, npm v5.6.0

Here is a screenshot of the output from running `npm test`. That repeating list of warnings at the top is related to [a recently opened issue with `istanbul`](https://github.com/istanbuljs/istanbuljs/issues/119). I am wondering is those warnings are somehow affecting the test coverage?

nyc error output

**Comment by jhowardjr** [comment]
Interesting! I'm going to see if I can reproduce it. Thanks!

**Comment by jmbothe** [comment]
UPDATE: After you merged this branch to `develop`, I pulled it down to my local clone, and now I am not getting the `ArrowFunctionExpression` warnings, but my test coverage is still off:


nyc error output 02

**Comment by jmbothe** [comment]
Sorry for commenting in small chunks, but I am learning this tool as I am trying to debug these issues. I figured out how to generate a detailed report in HTML format, and it looks like ALL of the statements that are coming up as `not covered` are arrow function expressions. So yea, I would say this issue that they are having over at istanbul is affecting the output. Why it is only happening on my machine, I don't know. What version of 

[here is the code coverage report in HTML format](https://jmbothe.github.io/istanbul-arrow-function-expression-bug/index.html)

**Comment by jmbothe** [comment]
Aaaaaaaaand, now for my final comment. I deleted `node_modules` folder, deleted `package-lock.json`, re-ran `npm install`, and now I am getting 100% test coverage across the board.

No idea how any of that is related, but there it is. I'm taking a break. hahaha

**Comment by jhowardjr** [comment]
Did you happen to install babel at any time?

**Comment by jmbothe** [comment]
no. I dont have a global installation, or a local installation of babel. the only reason it would be in the projects `node_modules` directory would be if it was a dependency of one of the other modules

**Comment by jmbothe** [comment]
I think I know what happened here. I found that running `npm dedupe` was leading to the issue with `ArrowFunctionExpression` warnings. I think it was moving Babel to a shallower directory and causing the conflict with `nyc`.

**Pull request merged**
